# Generated by Django 3.0.2 on 2020-08-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='user',
            field=models.CharField(default='', max_length=20),
        ),
    ]
