# Generated by Django 3.0.2 on 2020-08-16 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_buy_datetimefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='datetimefield',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 16, 23, 7, 52, 127612)),
        ),
        migrations.AlterField(
            model_name='buy',
            name='datetimefield',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 16, 23, 7, 52, 128608)),
        ),
    ]
