# Generated by Django 3.0.2 on 2020-08-16 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20200816_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='datetimefield',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 16, 23, 8, 19, 510097)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='datetimefield',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 16, 23, 8, 19, 510097)),
        ),
    ]
