# Generated by Django 3.1.4 on 2020-12-21 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20200816_2308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buy',
            options={'ordering': ['datetimefield'], 'verbose_name_plural': 'Buy'},
        ),
        migrations.AlterField(
            model_name='buy',
            name='datetimefield',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 21, 14, 6, 28, 963031)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='datetimefield',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 21, 14, 6, 28, 963031)),
        ),
    ]
