# Generated by Django 3.2 on 2021-04-21 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20201221_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='datetimefield',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 21, 10, 8, 44, 55097)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='datetimefield',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 21, 10, 8, 44, 55097)),
        ),
    ]
